- name: Deploy Tomcat 9 with sample.war
  hosts: localhost
  become: yes
  vars:
    env: "DEV"
    tomcat_version: 9
    jvm_heap: "{{ '256m' if env == 'DEV' else '512m' }}"
    tomcat_install_dir: /opt/tomcat

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - default-jdk
        - wget
        - unzip

    - name: Create Tomcat directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory

    - name: Download Tomcat 9
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz"
        dest: /tmp/tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Copy sample.war
      copy:
        src: /data/sample.war
        dest: "{{ tomcat_install_dir }}/webapps/sample.war"

    - name: Set JVM heap size
      lineinfile:
        path: "{{ tomcat_install_dir }}/bin/setenv.sh"
        create: yes
        line: 'export CATALINA_OPTS="-Xmx{{ jvm_heap }}"'

    - name: Find all .sh files in Tomcat bin directory
      find:
        paths: "{{ tomcat_install_dir }}/bin"
        patterns: "*.sh"
      register: tomcat_sh_scripts

    - name: Make all Tomcat .sh scripts executable
      file:
        path: "{{ item.path }}"
        mode: '0755'
        state: file
      loop: "{{ tomcat_sh_scripts.files }}"

    - name: Start Tomcat
      shell: "{{ tomcat_install_dir }}/bin/startup.sh"
